#!/bin/bash
pwd
echo shell $SHELL
echo WORKSPACE $WORKSPACE

rm -rf venv2
virtualenv venv2
source venv2/bin/activate
pip install pytest
echo "Start Testing"
pytest --junitxml=test-results/$BUILD_NUMBER.xml
#pytest --junitxml=../../jobs/test-python/test-results/$BUILD_NUMBER.xml
echo Done

