#!/bin/bash
pwd
echo shell $SHELL
echo WORKSPACE $WORKSPACE

rm -rf venv2
virtualenv venv2
source venv2/bin/activate
pip install pytest
echo "Start Testing"
#pytest
pytest --junitxml=test-results/$BUILD_NUMBER.xml
# echo Done and now?

pip install pylint
# export TERM="linux"
pylint  --rcfile=pylint.cfg $(find my -name "*.py" -print | grep -v 'tests' | grep -v '__init__') --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" > pylint.log || exit 0


