#!/bin/bash
pwd
echo shell $SHELL
echo WORKSPACE $WORKSPACE

rm -rf venv2
virtualenv venv2
source venv2/bin/activate
pip install pytest
echo "Start Testing"
#pytest
pytest --junitxml=test-results/$BUILD_NUMBER.xml
# echo Done and now?

pip install pylint
# export TERM="linux"
pylint $(find my -name "*.py" -print | grep -v 'tests' | grep -v '__init__') > pylint.log || exit 0
# --rcfile=pylint.cfg


